### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by norsivad** [marijnkampf/Random-Photo-Screensaver#101]
Running Win 7 Ultimate 64 bit. Throwing error Line 573 line 6 unexpectyed call to a ....... code 0

**Comment by norsivad** [comment]
Sorry. Line 513 character 6

**Comment by marijnkampf** [comment]
Thank you for your report. Does this happen everytime RPS runs? Which version of RPS are you using?

**Comment by norsivad** [comment]
Every time. I assume the latest version as we just downloaded it this week.

Ron Davis, Publisher
BlueBuffaloPress

LinkedIn Ron (NorSivad) Davis<https://goo.gl/wBM3SS>

**Comment by marijnkampf** [comment]
Could you please include the entire error message and double check the version you've installed?

**Comment by norsivad** [comment]
The version is the latest listed on your site download page.

The error is as we listed.

I have uninstalled the program but really liked it when it worked.

Ron Davis, Publisher
BlueBuffaloPress

LinkedIn Ron (NorSivad) Davis<https://goo.gl/wBM3SS>

**Comment by marijnkampf** [comment]
Unfortunately, what you posted is only part of an error message. I can't determine what the cause is without the full message. Feel free to re-open the issue if you decide to re-install RPS and receive another error message.
