### ISSUE TITLE
Start-up screensaver could be faster

### ISSUE THREAD

**Issue by rolfio** [marijnkampf/Random-Photo-Screensaver#108]
It takes a few seconds to load the screensaver. Could this be less time? Maybe even a shortcut to launch the screensaver

**Comment by marijnkampf** [comment]
I've optimised the screensaver to loads as quickly as possible. Or do you mean the inactivity timeout of windows?

> The screensaver start time is a setting in Windows. Please note that this is found in a different place than the RPS screensaver settings.
> 
> Windows XP:
> Go to Start > Settings > Control Panel > Display and select 'Screen Saver' tab.
> Windows 7:
> Go to Start > Control Panel\Appearance and Personalization > Change Screen Saver 
> You can set the start time out with: 'Wait XX minutes.'
