### ISSUE TITLE
Add picture to omition list

### ISSUE THREAD

**Issue by pqekypk2** [marijnkampf/Random-Photo-Screensaver#110]
Helllo

please add some option to have a omition list file and save it in a specific location. ah with one key add current picture to the omition list

Thanks

**Comment by marijnkampf** [comment]
The screen saver doesn't show hidden files, so you can press the H key to add the hidden attribute to a picture and it won't show up again. Would that suit your needs?

**Comment by pqekypk2** [comment]
But if i dont want to hide the file, becouse is my library folder, but i dont want to show it in my screen saver the option still have place.
Please help me

**Comment by marijnkampf** [comment]
If you don't want to hide files using the hidden attribute / H key shortcut, you could hide files with a certain image rating set. You can use the shortcut ctrl + 1 to set image rating 1. (You can reset it using ctrl + 0) and then add a filter to exclude all images with image rating set to 1.

To add the filter:

- Press S key whilst RPS is running to enter the configuration.
- Select the Filters tab
- In the Current Filter section select:
- Exclude metadata Containing rating\t1
  You can change the number of \t if you want to use a different rating number.
- Click Apply Filter
- Check Use Filters if not already checked.

You should now see DB ## images; filtered ## images; in the bottom left info bar.

Would this work better for your setup?

**Comment by pqekypk2** [comment]
perfect!
Thanks
