### ISSUE TITLE
RPS doesn't start, Win 10 screensavers do

### ISSUE THREAD

**Issue by dwlotter** [marijnkampf/Random-Photo-Screensaver#112]
Brand new Dell XPS 13, Win 10.  I saw advice to disconnect USBs.  I can't afford to take out USB connections, I need them.
I also re-started the computer, to no avail.
I looked for posts on this issue on github.  One said use the Win screensaver then go back to RPS, but that doesn't work.
Advice would be greatly appreciated.
Don

**Comment by marijnkampf** [comment]
Does RPS start from the shortcut on your system? Which version of RPS and Internet Explorer do you have installed?

**Comment by marijnkampf** [comment]
Are you still having the same issue?

**Comment by dwlotter** [comment]
Thanks for checking.  It is not starting. Windows screensaver starts no
problem.
Don

[image: image.png]

**Comment by marijnkampf** [comment]
I'm scratching my head here to find a cause. You seemed to have checked/ruled out the obvious ones. Which version of Windows 10 do you use? Do you have any anti virus / firewalls installed?

**Comment by dwlotter** [comment]
[image: image.png]
[image: image.png]

**Comment by marijnkampf** [comment]
I'm afraid I can't see the images you attached. It just shows:

[image: image.png]
[image: image.png]

**Comment by dwlotter** [comment]
I'm running Windows Defender.

[image: defender.JPG]

[image: This Windows System.JPG]

**Comment by marijnkampf** [comment]
I still can't view the images.
