### ISSUE TITLE
Pause function onto numeric keypad

### ISSUE THREAD

**Issue by VicMildew** [marijnkampf/Random-Photo-Screensaver#118]
I use this fabulous screensaver prog a lot. There are only 5 functions needed to sit and enjoy it from your armchair! Cursor up, down, left and right AND the P for pause, which allows videos to be watched for the full length regardless of how long the normal slideshow time is set for.

A keyboard is too big to comfortably have on the arm of the chair so I have a small numeric keypad, which does all required EXCEPT the pause function! 

Is it possible to allocate a pause function onto one of the unused numbers, 3 or 9.

On my keypad I also have 0 /  * - + Backspace and Enter if 3 or 9 wasn't advisable!

Hope you can keep the magic working!

**Comment by marijnkampf** [comment]
Thank you for your feedback. Please see issue #79 which is on my to do list!
