### ISSUE TITLE
Everyday hang with 100% CPU usage

### ISSUE THREAD

**Issue by vale-sys** [marijnkampf/Random-Photo-Screensaver#123]
Hi, 
I am using Windows 7 x32 and Random-Photo-Screensaver on it. Every day I see hang errors with 100% CPU usage. RPS configured to use one picture folder with 44 906 files split to 46 folders (one folder ~ 1000 files). The problem considers only my 32-bit laptop. Attached event logs, RPS logs, and app folder with an internal database. Can somebody explain where the problem?

[Random Photo Screensaver.zip](https://github.com/marijnkampf/Random-Photo-Screensaver/files/3899322/Random.Photo.Screensaver.zip)

[error_1.txt](https://github.com/marijnkampf/Random-Photo-Screensaver/files/3899315/error_1.txt)
[error_2.txt](https://github.com/marijnkampf/Random-Photo-Screensaver/files/3899317/error_2.txt)

![err1](https://user-images.githubusercontent.com/58278158/69769063-46454c00-1194-11ea-98ba-cb8df90c6864.png)
![err2](https://user-images.githubusercontent.com/58278158/69769078-50ffe100-1194-11ea-9c68-3439bf4ceb08.png)

**Comment by marijnkampf** [comment]
Could you try removing the meta.sqlite and store.sqlite databases and re-running RPS? RPS will re-index all the files it can find.
