### ISSUE TITLE
RPS corrupted after recent Windows update, possibly to 19042

### ISSUE THREAD

**Issue by shadonoz** [marijnkampf/Random-Photo-Screensaver#135]
Just wanted to report that RPS became very sluggish to load, and kept deteriorating, until it wouldn't launch at all.
But no worries, I reinstalled and all is well.
In case it happens to anyone else.

**Comment by marijnkampf** [comment]
Thanks for your feedback.

**Comment by shadonoz** [comment]
It turns out my problem had nothing to do with RPS.  I had a network drive mapped on my main system.  Whenever the remote system was offline, RPS (and MultiCommander, my file manager) would choke whenever they started.  I discovered that when I disconnect from that mapped drive, both programs open quickly, as expected.  There is no problem when the remote system is online.

I think this must be a bug introduced in Win 10 home 20H2 build 19042.928 because the behavior began just after the upgrade.
