### ISSUE TITLE
Option/shortcut to be able to star/favourite a photo while slideshow running

### ISSUE THREAD

**Issue by razvan73** [marijnkampf/Random-Photo-Screensaver#17]
Hi,
I would find very useful to be able to star/favourite/rate images while screen saver is running, wthout interrupting the slide show.

Thanks a lot for your great work!

**Comment by marijnkampf** [comment]
Thanks you for your suggestion.

How would you like to see an image marked as favourite? Is there a specific metatag you would like adding?

**Comment by razvan73** [comment]
If it is possible, one way I would see it acheived is to e.g. when hitting numeric '1' - '5' keys while the slideshow is running, the photo to get the corresponding rating (and Rating metatag to be updated with this value; for being able to select later, even in Explorer, the photos with a certain rating.) 

Thank you so much!

**Comment by marijnkampf** [comment]
Thanks for your feedback. Will probably end up using F1 - F5, Numpad numbers or ctrl+1-5 / alt+1 - 5, as the regular numbers are used to select screens on multi monitor setup (do you have a preference?). 
Note to myself: http://www.exiv2.org/tags.html
0x4746 	18246 	Image 	Exif.Image.Rating 	Short 	Rating tag used by Windows

**Comment by razvan73** [comment]
*Numpad numbers* 1-5 would do it ok for me.

Thanks a million!

(Side question: would it be possible to set up a filter to play all images
e.g. with Rating = 5?)

**Comment by marijnkampf** [comment]
Yes you can filter on ratings, for now you'll have to use a __raw SQL filter__ with the content:
```
`all` LIKE "%Rating	5%"
```
Note there is a __tab__ not a space between Rating and the value.

**Comment by marijnkampf** [comment]
Rating images has been implemented in RPS 4.4. Use shortcut Ctrl + 0 ... 5. Numpad conflicted with earlier shortcuts and having to use ctrl + number should avoid accidental rating, of course ratings can be completely disabled from settings.

Try adding the following to the [QuickMetadata](http://www.abscreensavers.com/random-photo-screensaver/configuration/?tab=metadata):
<#<div class='rating r{Rating}'>{Rating} stars</div>#>

**Comment by razvan73** [comment]
Looks great, thanks!
