### ISSUE TITLE
Need help with correct usage of filters

### ISSUE THREAD

**Issue by rwburbage** [marijnkampf/Random-Photo-Screensaver#24]
First I want to say thank you for such an awesome program.  I've been looking for a program to display family photos easily with filtering and or folder selection. Great work!  I have a tremendous amount of family photos and I want to filter out any path or files names with 1,2 or more words. I've tried a number of way with apply filters, save the filter, save button and I can't seem to filter out photos names or paths.   for example the paths and or filenames will contain 2 words to filter "mummy player" as a string in that order. Do I need to add quotes for exclude-paths-containing-"mummy player".  I've tried that and it doesn't work either.  I'm assuming I need to 'add filter dimension' for each filter correct?  I have about 10 filters added.  The save filter sql look fine but I test and the unwanted photos pop up with paths or filenames with mummy player in them.

**Comment by rwburbage** [comment]
AS soon as I leave a help message I tried again.  The filters are case sensitive...

**Comment by marijnkampf** [comment]
The filter names shouldn't be case sensitive, there is probably something else going on. If you create a filter:
````
Exclude paths Containing mummy player
````
it **will exclude**
````
c:\mummy player\example.jpg
c:\Mummy Player\example.jpg
c:\example\001 mummy player.jpg
c:\example\001 Mummy Player.jpg
````
but not 
````
c:\mummy\player\example.jpg
c:\example\mummy\player.jpg
````
There is a \ between folder/file names, to exclude this add another dimension:
Exclude paths Containing mummy\player

PS. Clicking on 'Show advanced settings...' shows an overview of the dimensions that can me used:
The following dimensions can be used in filters: **[database column]** [description]
**paths** full path (folder and filename)
**parent** paths folder path only
**filenames** filename (including extension)
**created** date created date
**modified** date modified date
**metadata** all metadata of media
**size** file size
**width** width of the media in pixels
**height** height of the media in pixels
**area** pixel width x height of the media
