### ISSUE TITLE
Zoom and Pan / Ken Burns effect

### ISSUE THREAD

**Issue by samchan88** [marijnkampf/Random-Photo-Screensaver#27]
Please take note that Zoom and Pan / Ken Burns effect no more working after you had added:
    this.screensaver.config.hasPersistantKey("effect")
to monitor.cs.

**Comment by marijnkampf** [comment]
The latest version 4.5.6.4 ( http://www.abscreensavers.com/random-photo-screensaver/ ) should fix that and hopefully won't have introduced any other bugs.
