### ISSUE TITLE
Script Errors in RPS

### ISSUE THREAD

**Issue by NoCrossBar** [marijnkampf/Random-Photo-Screensaver#37]
Hi Marijn.  Can you help?
I am having the following script errors when I run Configure Random Photo Screensaver.

![26909-3](https://cloud.githubusercontent.com/assets/13499657/8890707/309f663a-3302-11e5-8b60-ab4af8e16e15.JPG)
![434-5](https://cloud.githubusercontent.com/assets/13499657/8890709/34b5168e-3302-11e5-98fa-e49bcd17ee0a.JPG)

The machine is running Win7N 64bit, with three monitors.  Not sure what other information you need.
Many Thanks
Marek

**Comment by marijnkampf** [comment]
Hi Marek,

Thank you for your report, please install http://www.abscreensavers.com/abdownloads/rps/old/setup-rps4.5.8.1.exe to fix the above errors.

Marijn.
