### ISSUE TITLE
Screensaver not automatically starting

### ISSUE THREAD

**Issue by tbranson303** [marijnkampf/Random-Photo-Screensaver#41]
I've installed on 10 computers and have some that will not automatically start. 

All computers are windows 7 64-bit.

**Comment by marijnkampf** [comment]
Which version of RPS are you using?

To get RPS starting automatically again you could try:

* Go to Personalize > Screen Saver.
* Select (none) as Screen Saver and click Apply.
* Reselect Random Photo Screensaver and click Ok.

**Comment by tbranson303** [comment]
It's version 4.5.9, the computers orignally had XP and were upgraded to windows 7 ultimate, would this make any difference?
 -------------------------------------------------------------------------------
Tell us how we are doing!  Leave us a comment and like us on our facebook page!https://www.facebook.com/drkenbranson-------------------------------------------------------------------------------Thanks,
Todd BransonOffice Manager
Branson Dentalwww.drkenbranson.comT - 817-285-8825

**Comment by marijnkampf** [comment]
No the version query is for my info. Setting RPS as the current screensaver from the installer has contained a bug causing the symptoms you described. I thought  4.5.9 fixed it, but apparently not :(
