### ISSUE TITLE
Add Random features : new images more likely to appear

### ISSUE THREAD

**Issue by Adrien05** [marijnkampf/Random-Photo-Screensaver#43]
Hi,
First, bravo for the good work !

I am currently testing your great screensaver on a 7000+ photos directory (family pictures...).
I am a bit annoyed by the fact that newer picture never appear : only old pictures are shown :-(
Since 2006, I have around 8 sub-directories per year full of pictures. Since I tested the screensaver, I only had 2006 or 2007 pictures. Nothing older.
Of course, I used the option Random in the Slideshow section...

Is there a way to give a little a bit of weight on this criteria on the random feature ?

Many thanks in advance...

PS: Current advanced settings are:
- Remember 10000
- Maximum random history size : 1000000
But I tried 100 / 10000

**Comment by marijnkampf** [comment]
The Random function is truly random, as there are fewer "new" photos then "old" photos old photos are more likely to appear.

To rule out the possibility of not all photos being found by RPS, does the number of photos detected tally with the total number of images in your photo folder?

If this tallies, you could try the + Similar time of year filter from http://www.abscreensavers.com/random-photo-screensaver/faq/#filters to see more recent photos.

PS. the advanced settings you mentioned only apply to navigating through the photos. They do not alter the selection made.

PSS. I've got a similar setup with 30000+ and folders from 2003 - 2015 (and sub folders containing days out) recent photos do show up.

**Comment by Adrien05** [comment]
Actually, it now seems OK. Does it need a long time to record all pictures in the sub-folders ?
How do I know the number of photos detected ?

**Comment by marijnkampf** [comment]
You can see a count at the bottom left of the screensaver when running. Once a file is in the RPS database it might be shown. On my systems with 34,000+ files in 1,900 folders it takes under two minutes to scan all files.

DB: #Number of files currently in the database# 
Scanned: #Number of files scanned on this run#

You might see a countdown of each newly detected file's metadata being read, this is also stored to allow filtering on metadata.
