### ISSUE TITLE
slideshow order keeps going to sequential (from random)

### ISSUE THREAD

**Issue by nihilojack** [marijnkampf/Random-Photo-Screensaver#44]
In the settings, I choose random order, then for some unknown reason, a while later, the slideshow goes back to sequential.  Windows 10 machine, can't figure out why the slideshow keeps jumping to sequential.

**Comment by marijnkampf** [comment]
Hi nihilojack,
Which version of RPS are you using? (Press S whilst the screensaver is running to enter configuration screen)

**Comment by nihilojack** [comment]
Hi Marijn,

This is the version I'm using - RPS 4.5.9 (IE:11.0).   It works ok for a
few days, then for some reason, it changes to sequential.  I can't figure
out what triggers it, I don't think it's anything that I'm doing.   It was
fine for the last several days, and tonight it did it again.  Not a huge
issue, just weird.  I have to go in and change it back to random, but still
I don't know what makes it go to sequential.

Thanks,
Mark

P.S.  Great program, btw.

**Comment by marijnkampf** [comment]
Hi Mark,

I presume all other settings are retained when it changes. Are you aware that pressing the R key whilst the screensaver is running will change between Sequential and Random? 

Best wishes,

Marijn.

**Comment by nihilojack** [comment]
Marijn,

I think that's the issue.  Sometimes my kids want to look at certain pics
in sequence, so they press the up and down arrows, and those are located
right next to the '1' on the number pad (the other shortcut to switch
random/seq).  So I think they press the 1 by mistake.  Now I know.

Thanks for your help.  Hello from Atlanta, Georgia.
