### ISSUE TITLE
Enable "lock workstation" upon exit

### ISSUE THREAD

**Issue by upacrk1** [marijnkampf/Random-Photo-Screensaver#48]
Hi!
   I just discovered your screensaver software and am testing it.  So far I like it, but I find a feature missing - upon exiting the screensaver display, it would be great to lock the computer (ie, C:\Windows\System32\rundll32.exe user32.dll, LockWorkStation).  I hope this will be an included option in some future version.

Thanks much!

Mike

**Comment by marijnkampf** [comment]
As far as I know this facility is provided by Windows in Screen Saver Settings if you check the option: On resume, display logon screen. (Start > Control Panel > Control Panel > Appearance and Personalization > Change Screensaver)

**Comment by upacrk1** [comment]
Hi Marijn!     Yes, you're right.  I've had it checked when I was using the default MS photo screensaver.  I just realized that the installation of your software had unchecked it (the default, I think).  I now have it checked and everything works as expected.  Thanks for the speedy reply and for the great software!
Regards,Mike Thommes

**Comment by marijnkampf** [comment]
Hi Mike Thommes,

The RPS installation shouldn't influence the logon setting, which version of Windows are you using?

Cheers,

Marijn.

**Comment by upacrk1** [comment]
Hi,    I'm running Windows 7 Home Premium with SP1.
Mike

**Comment by marijnkampf** [comment]
Thanks. If anyone experiences this issue again, please add another comment to this topic.
