### ISSUE TITLE
Pan and zoom (Ken Burns effect)

### ISSUE THREAD

**Issue by marijnkampf** [marijnkampf/Random-Photo-Screensaver#5]

**Comment by radoma** [comment]
Google Screensaver has this. I miss it in Random Photo Screensaver :(

**Comment by marijnkampf** [comment]
Try version 4.5.6.1 http://www.abscreensavers.com/random-photo-screensaver/

**Comment by marijnkampf** [comment]
Seems to be very buggy, so reverting the release.

**Comment by marijnkampf** [comment]
Third time lucky, try version 4.5.6.3 http://www.abscreensavers.com/random-photo-screensaver/
