### ISSUE TITLE
Browsing with right mouse click opens browser's popup menu

### ISSUE THREAD

**Issue by marijnkampf** [marijnkampf/Random-Photo-Screensaver#59]
to configure the keyboard and mouse is not working "Use mouse to browse", because with the right mouse click opens a standard dialog browser.

setup-rps4.5.9.2.exe
windows 7 x64

**Comment by marijnkampf** [comment]
Will be fixed in next release RPS 4.5.10.1

**Comment by bypsix** [comment]
I confirm, right mouse click works correctly (sometimes it opens dialogue box is displayed Windows Media Player settings, but very rarely, comfortable viewing this does not prevent)
