### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by Cravenplan** [marijnkampf/Random-Photo-Screensaver#62]
Hi,

When I view the settings page I get a corrupted screen.

Chris
![clipboard01](https://cloud.githubusercontent.com/assets/17945511/13897859/19501490-edb8-11e5-951f-c34006573b3d.jpg)

**Comment by marijnkampf** [comment]
It looks like the stylesheets are missing, can you try reinstalling RPS?

**Comment by Cravenplan** [comment]
I did reinstall but it made no difference

**Comment by marijnkampf** [comment]
If you open %ProgramData%\Random Photo Screensaver\data\config.html in Internet Explorer does it show correctly?

If not is there a subfolder %ProgramData%\Random Photo Screensaver\data\css and which files does it contain?

Also to try, in Internet Explorer do you have style sheets disabled by any change?

**Comment by Cravenplan** [comment]
Hi,

It does not show in Internet Explorer although 
when using Opera (my default browser) it does 
show correctly.   Also displays in Firefox and 
Chrome.  None f these browsers allow the saving of the settings though.

I checked the registry for IE and the value for 
style sheets wasn't there so I created it but still no good.

In Internet Explorer I get the message "Internet 
Explorer restricted this webpage from running 
scripts or ActiveX Controls"  Even when I click 
the "Allow blocked content" button the screen is not displayed correctly.

The CSS subfolder does exist - it contains three 
files - _custom.monitor.css + monitor.css + config.css

Chris



At 17:56 24/03/2016, Marijn Kampf wrote:

>If you open %ProgramData%\Random Photo 
>Screensaver\data\config.html in Internet Explorer does it show correctly?
>
>If not is there a subfolder %ProgramData%\Random 
>Photo Screensaver\data\css and which files does it contain?
>
>Also to try, in Internet Explorer do you have 
>style sheets disabled by any change?
>
>­
>You are receiving this because you authored the thread.
>Reply to this email directly or 
><https://github.com/marijnkampf/Random-Photo-Screensaver/issues/62#issuecomment-200949537>view 
>it on GitHub




***** HOPE AND HOMES EVENTS *****
As you may know, as Chairman of the Wiltshire 
Support Group, I am passionate about the charity Hope and Homes for Children
(UK Registered Charity 1089490, http://www.hopeandhomes.org).
The following events are being held in aid of 
Hope and Homes over the next few months 
http://www.hhc-sw.com (Book tickets by calling me (Chris) on 01747 858016):



***** Cut price Picture Frames *****
Picture Frames in Shaftesbury are offering very 
cut price picture frames with 50%, 75% and even 
100% of the price in some cases, being donated to 
Hope and Homes for Children.  Pick up some great 
bargain frames in the knowledge that you're 
helping a great charity at the same time.
Friday 6th May and Saturday 7th May 2016 (09:00-17:00)
Unit 26, The Wincombe Centre, Shaftesbury, Dorset, SP7 9QJ
Tel: 01747 858357
Web site: www.pictureframes.co.uk



***** EU Referendum Debate *****
The Swallowcliffe Debating Society is holding 
another Question Time evening during the run up 
to the most important referendum this century.
It will be free (with a collection for Hope and Homes for Children)
17th June 2016 (8pm)
More info at http://www.swallowcliffe.com/debating.htm


***** Jazz 2016 *****
Pete Allen's All Star Jazz Band at Winterbourne 
Dauntsey - Saturday 23rd July 2016 - 19:00 - £20



***** Tea Tasting 2016 *****
A unique opportunity to hear from an expert in 
tea in the beautiful gardens at Winterbourne 
Dauntsey - Sunday 24th July 2016 - 15:00 - £10
Enjoy a lovely home made cream tea in the sunshine for £5



Chris Stanbury
Managing Director

T: +44 (0)1747 858000
E: chris@cravenplan.co.uk

Twitter: <https://twitter.com/CravenplanChris>@CravenplanChris

Web site: www.cravenplan.co.uk

Cravenplan Computers Limited is a company 
registered in England and Wales with company number 1830366
Registered at Wilbury Barn, Swallowcliffe, Salisbury, Wilts, SP3 5QH
Our VAT number is GB 409 8139 37

**Comment by marijnkampf** [comment]
Hi Chris,

Sorry I might have not been clear. RPS uses Internet Explorer internally for displaying photos / videos and the settings screen. As the settings pages aren't shown in IE it tells me the issue is with your IE setup. Unfortunately, it won't work directly from a browser, and RPS requires IE to work as it's the only one that intergrates with C# and Visual Studio.

Do you see regular website such as www.abscreensavers.com correctly from within IE? Or are stylesheets missing there too?

**Comment by Cravenplan** [comment]
Hi,

Other sites were working fine.

I tried disabling and then up dating IE but it is 
now broken!  On my main PC it won't let me 
install a new copy as it says a newer one exists 
but I can't run it.  So, experiments on that PC have ended.

I have run RPS on a second PC and it works on there.

Chris


At 11:07 26/03/2016, Marijn Kampf wrote:

>Hi Chris,
>
>Sorry I might have not been clear. RPS uses 
>Internet Explorer internally for displaying 
>photos / videos and the settings screen. As the 
>settings pages aren't shown in IE it tells me 
>the issue is with your IE setup. Unfortunately, 
>it won't work directly from a browser, and RPS 
>requires IE to work as it's the only one that 
>intergrates with C# and Visual Studio.
>
>Do you see regular website such as 
><http://www.abscreensavers.com>www.abscreensavers.com 
>correctly from within IE? Or are stylesheets missing there too?
>
>­
>You are receiving this because you authored the thread.
>Reply to this email directly or 
><https://github.com/marijnkampf/Random-Photo-Screensaver/issues/62#issuecomment-201751131>view 
>it on GitHub




***** HOPE AND HOMES EVENTS *****
As you may know, as Chairman of the Wiltshire 
Support Group, I am passionate about the charity Hope and Homes for Children
(UK Registered Charity 1089490, http://www.hopeandhomes.org).
The following events are being held in aid of 
Hope and Homes over the next few months 
http://www.hhc-sw.com (Book tickets by calling me (Chris) on 01747 858016):



***** Cut price Picture Frames *****
Picture Frames in Shaftesbury are offering very 
cut price picture frames with 50%, 75% and even 
100% of the price in some cases, being donated to 
Hope and Homes for Children.  Pick up some great 
bargain frames in the knowledge that you're 
helping a great charity at the same time.
Friday 6th May and Saturday 7th May 2016 (09:00-17:00)
Unit 26, The Wincombe Centre, Shaftesbury, Dorset, SP7 9QJ
Tel: 01747 858357
Web site: www.pictureframes.co.uk



***** EU Referendum Debate *****
The Swallowcliffe Debating Society is holding 
another Question Time evening during the run up 
to the most important referendum this century.
It will be free (with a collection for Hope and Homes for Children)
17th June 2016 (8pm)
More info at http://www.swallowcliffe.com/debating.htm


***** Jazz 2016 *****
Pete Allen's All Star Jazz Band at Winterbourne 
Dauntsey - Saturday 23rd July 2016 - 19:00 - £20



***** Tea Tasting 2016 *****
A unique opportunity to hear from an expert in 
tea in the beautiful gardens at Winterbourne 
Dauntsey - Sunday 24th July 2016 - 15:00 - £10
Enjoy a lovely home made cream tea in the sunshine for £5



Chris Stanbury
Managing Director

T: +44 (0)1747 858000
E: chris@cravenplan.co.uk

Twitter: <https://twitter.com/CravenplanChris>@CravenplanChris

Web site: www.cravenplan.co.uk

Cravenplan Computers Limited is a company 
registered in England and Wales with company number 1830366
Registered at Wilbury Barn, Swallowcliffe, Salisbury, Wilts, SP3 5QH
Our VAT number is GB 409 8139 37

**Comment by marijnkampf** [comment]
If the issue is with Internet Explorer, I'm afraid I won't be able to help. You could try http://windows.microsoft.com/en-gb/internet-explorer/internet-explorer-help

**Comment by Cravenplan** [comment]
Thanks


At 17:34 29/03/2016, you wrote:

>If the issue is with Internet Explorer, I'm 
>afraid I won't be able to help. You could try 
><http://windows.microsoft.com/en-gb/internet-explorer/internet-explorer-help>http://windows.microsoft.com/en-gb/internet-explorer/internet-explorer-help
>
>­
>You are receiving this because you authored the thread.
>Reply to this email directly or 
><https://github.com/marijnkampf/Random-Photo-Screensaver/issues/62#issuecomment-202987494>view 
>it on GitHub




***** HOPE AND HOMES EVENTS *****
As you may know, as Chairman of the Wiltshire 
Support Group, I am passionate about the charity Hope and Homes for Children
(UK Registered Charity 1089490, http://www.hopeandhomes.org).
The following events are being held in aid of 
Hope and Homes over the next few months 
http://www.hhc-sw.com (Book tickets by calling me (Chris) on 01747 858016):



***** Cut price Picture Frames *****
Picture Frames in Shaftesbury are offering very 
cut price picture frames with 50%, 75% and even 
100% of the price in some cases, being donated to 
Hope and Homes for Children.  Pick up some great 
bargain frames in the knowledge that you're 
helping a great charity at the same time.
Friday 6th May and Saturday 7th May 2016 (09:00-17:00)
Unit 26, The Wincombe Centre, Shaftesbury, Dorset, SP7 9QJ
Tel: 01747 858357
Web site: www.pictureframes.co.uk



***** EU Referendum Debate *****
The Swallowcliffe Debating Society is holding 
another Question Time evening during the run up 
to the most important referendum this century.
It will be free (with a collection for Hope and Homes for Children)
17th June 2016 (8pm)
More info at http://www.swallowcliffe.com/debating.htm


***** Jazz 2016 *****
Pete Allen's All Star Jazz Band at Winterbourne 
Dauntsey - Saturday 23rd July 2016 - 19:00 - £20



***** Tea Tasting 2016 *****
A unique opportunity to hear from an expert in 
tea in the beautiful gardens at Winterbourne 
Dauntsey - Sunday 24th July 2016 - 15:00 - £10
Enjoy a lovely home made cream tea in the sunshine for £5



Chris Stanbury
Managing Director

T: +44 (0)1747 858000
E: chris@cravenplan.co.uk

Twitter: <https://twitter.com/CravenplanChris>@CravenplanChris

Web site: www.cravenplan.co.uk

Cravenplan Computers Limited is a company 
registered in England and Wales with company number 1830366
Registered at Wilbury Barn, Swallowcliffe, Salisbury, Wilts, SP3 5QH
Our VAT number is GB 409 8139 37
