### ISSUE TITLE
Precaching and path font

### ISSUE THREAD

**Issue by firesword-bg** [marijnkampf/Random-Photo-Screensaver#70]
Hello,
I like your program very much, it is just what I was looking for months. I even donated.
I have a polite request, if possible for 2 features:

1. All my pictures are on the WiFi home network, so when the program loads a new picture it takes 1-2-3 seconds to load it through the wifi, and it is not good. Can the program pre-load the next picture? And then when it is time to show it, to have it already downloaded in memory.

2. I like the feature to see the file path. It helps me see when and where the picture was taken. however I do not see a way to control the size or color of the text.

Thanks and go on with your fantastic work!
Ilian

**Comment by marijnkampf** [comment]
Hi Illian,

For your first point see enhancement #3. Please add a comment to that issue to 'vote' for it.

For the second one please see http://www.abscreensavers.com/random-photo-screensaver/faq/#custommonitorcss

Best wishes,

Marijn.
