### ISSUE TITLE
RPS 10.4.5.1 Win10 hangs on .MPG, and ignores Video Extensions advanced prop

### ISSUE THREAD

**Issue by delovelady** [marijnkampf/Random-Photo-Screensaver#74]
Using RPS 10.4.5.1 on Win10 64 bit, the Video Extensions advanced setting seems to be ignored.  Adding to this, the saver hangs on .mpg files.  So I only get about 15-20 minutes of RPS activity before the saver hangs, and only Ctrl+Alt+Del seems to recover it.  

I have changed the Video Extensions to this in order to circumvent the problem:
.avixx .wmvxx .movxx .mp4xx .mpegxx .mpgxx

(There are no files on the system with these extensions; I've simply supplied them as placeholders hoping I can restore full function later.)

But even though this is the complete list of Video Extensions, the saver still hangs after a short time, with some .mpg fille listed as the "current file" at the top left of the screen.

Note that there is a small movie-like dialog in the middle of the screen when this happens, along with video controls, but the video does not seem to ever start.

**Comment by marijnkampf** [comment]
Could you try deleting store.sqlite and metadata.sqlite from %programdata%\Random Photo Screensaver\ and seeing whether RPS still picks up mpg files?

**Comment by delovelady** [comment]
Thank you very much.  Although it does still pop up a video for .mpg files now and then, it no longer hangs.  I appreciate the quick response!
