### ISSUE TITLE
Slideshow stalls on XP machine

### ISSUE THREAD

**Issue by AviationAce** [marijnkampf/Random-Photo-Screensaver#86]
I have a PC running Windows XP.  I use it mostly as just a file server for many things.  I also use it for a slideshow of photos.
I have tried versions 4.5 and 4.5.10.1.

The symptom:  It just stalls.  No error message or anything like that.

Questions:
Is there a way to make it more XP friendly?
Would an earlier version be more XP friendly?

**Comment by marijnkampf** [comment]
You are better of trying the 3.x version for use on Windows XP (http://www.abscreensavers.com/random-photo-screensaver/version-information/rps3/version-information/). 

XP was supported and tested for earlier 4.x versions but I no longer test the 4.x releases on XP.

**Comment by marijnkampf** [comment]
If you do want to try using RPS 4.x make sure you have the highest possible version of Internet Explorer installed on XP.

**Comment by AviationAce** [comment]
Thanks!  I'll try the 3.x version.
