### ISSUE TITLE
Repeating photos

### ISSUE THREAD

**Issue by djtentman** [marijnkampf/Random-Photo-Screensaver#89]
I have it set to "sequential" instead of random. At night, my PC is scheduled to hibernate, In the morning when it starts, it just repeats the photos over again. I have about 30,000 photos.

**Comment by marijnkampf** [comment]
With the info field that shows the number of images indexed at the bottom left of the screen, do you see a message saying Read Only - RPS is already running?

**Comment by PhantomMod** [comment]
Mine says "DB 186 images; Read Only - RPS is already running" and I too am having problems with constantly repeating photos. The ones repeating are all from 3 folders beginning with the letter A. I have the slideshow order set to random.

**Comment by marijnkampf** [comment]
@PhantomMod make sure there is only one version of RPS running. If it's in Read Only mode it won't store any additional photos found.
